// Auto-generated by AclnnBackend. DO NOT EDIT.
#include "acl/acl.h"
#include "Runtime/AclnnOps.h"
#include <cstdint>
#include <cstring>

using TensorInfo = mlir::runtime::aclnn::TensorInfo;
using mlir::runtime::aclnn::run_FlashAttentionScore;


static void network_impl(
    TensorInfo inputs[], int /*numInputs*/,
    TensorInfo outputs[], int /*numOutputs*/,
    aclrtStream stream) {
  TensorInfo t0; // tensor.empty — allocate at runtime
  TensorInfo t1;
  run_FlashAttentionScore(inputs[0], inputs[1], inputs[2], inputs[3], t0, &t1, stream);
  outputs[0] = t1;
}

extern "C" void network(
    TensorInfo inputs[], int numInputs,
    TensorInfo outputs[], int numOutputs,
    aclrtStream stream) {
  // Try aclInit; if it fails (e.g. running on CPU sim with no NPU
  // device available), fall through in host-mode so aclnn ops dispatch
  // to AclnnOps.cpp's CPU-reference implementations.
  static bool initialized = false;
  if (!initialized) {
    initialized = true;
    if (aclInit(nullptr) != 0) {
      mlir::runtime::aclnn::setHostMode(true);
    }
  }
  network_impl(inputs, numInputs, outputs, numOutputs, stream);
}
