function(resolve_ascend_cann_arch_dir out_var)
  set(_ascend_cann_arch "")
  set(_ascend_processor "${CMAKE_SYSTEM_PROCESSOR}")
  if(_ascend_processor STREQUAL "")
    set(_ascend_processor "${CMAKE_HOST_SYSTEM_PROCESSOR}")
  endif()
  if(_ascend_processor MATCHES "^(x86_64|amd64)$")
    set(_ascend_cann_arch "x86_64-linux")
  elseif(_ascend_processor MATCHES "^(aarch64|arm64)$")
    set(_ascend_cann_arch "aarch64-linux")
  endif()
  set(${out_var} "${_ascend_cann_arch}" PARENT_SCOPE)
endfunction()
