"""g++ link helper for generated network_host.cpp + generic harness.cpp.

Used by network_runner.py Phase 3 / Phase 5.

Sources compiled directly (no pre-built static lib) to avoid pulling in the
full CANN tiling/matmul stack from libAscendCRuntime.a:
  - network_host.cpp  (generated by aclnn-backend)
  - harness.cpp       (runner_utils/harness.cpp)
  - HostLaunchHelper.cpp, NativeExecutionRunner.cpp, NpyIO.cpp,
    TilingSchema.cpp, TilingPack.cpp, PathUtils.cpp  (runtime support)
  - AclnnOps.cpp      (always included; aclnn host-mode fallback path)

CANN libs required at link time — must match what tools/runtime-session links
against (see ninja -t commands runtime-session). Missing any of these means
the simulator runtime can't initialize at execution time even if linking
"succeeds" (libascendcl pulls in libruntime.so for the real-NPU side, which
masks the sim-mode rtSetDevice symbols).
"""
import os
import platform
import subprocess
from pathlib import Path

# Build-host architecture: pick the CANN arch dir and devlib subdir to match the
# machine actually running g++ (x86 dev box vs aarch64 real-NPU container).
_MACHINE = platform.machine()
_HOST_CANN_ARCH = "aarch64-linux" if _MACHINE in ("aarch64", "arm64") else "x86_64-linux"
_HOST_DEVLIB_ARCH = "aarch64" if _MACHINE in ("aarch64", "arm64") else "x86_64"


def link_host(
    host_cpp: Path,
    harness_cpp: Path,
    out_binary: Path,
    repo_root: Path,
    cann_home: str,
    cann_arch: str = _HOST_CANN_ARCH,
    soc: str = "Ascend910B1",
    has_aclnn_ops: bool = False,
    extra_sources: tuple = (),
    extra_libs: tuple = (),
) -> None:
    """Compile host_cpp + harness_cpp and link into a runnable binary."""
    cann_inc       = f"{cann_home}/{cann_arch}/include"
    cann_lib       = f"{cann_home}/{cann_arch}/lib64"
    # devlib/linux/x86_64/ has the x86_64 libascend_hal.so. (devlib/ root and
    # lib64/device/lib64/ have aarch64 versions on x86 hosts — wrong arch.)
    # Per examples/env.sh: lib64 must precede devlib in LD_LIBRARY_PATH so
    # libmetadef.so resolves to the lib64 version (devlib's is stripped of ge::
    # symbols). Same ordering applies at link time.
    cann_devlib    = f"{cann_home}/{cann_arch}/devlib/linux/{_HOST_DEVLIB_ARCH}"
    sim_lib        = f"{cann_home}/{cann_arch}/simulator/{soc}/lib"
    llvm_build     = os.environ.get("LLVM_BUILD_DIR") or str(repo_root / "externals/llvm-project/build")
    llvm_lib       = f"{llvm_build}/lib"
    llvm_inc       = str(repo_root / "externals/llvm-project/llvm/include")
    llvm_build_inc = f"{llvm_build}/include"

    # Runtime support sources compiled directly — but HostLaunchHelper now
    # routes through ExecutionSession::run, which transitively needs
    # TaskGraph, SimBackend, scheduler, etc. Pull those (and HostLaunchHelper
    # itself) from the prebuilt libAscendCRuntime.a; ar archives are
    # symbol-driven so the unused matmul/mix tiling stack stays out.
    runtime_sources = [
        str(repo_root / "lib/Runtime/AclnnOps.cpp"),
    ]

    sources = [str(host_cpp), str(harness_cpp)] + runtime_sources
    sources.extend(str(s) for s in extra_sources)
    ascendc_runtime_a = str(repo_root / "build/lib/libAscendCRuntime.a")

    # CANN libs — same set runtime-session links against (see ninja -t commands
    # runtime-session). Order matters for static-lib resolution; keep simulator
    # libs before lib64 so libruntime_camodel.so wins over libruntime.so.
    cann_libs = [
        "tiling_api", "register", "platform", "ascendalog", "unified_dlog",
        "runtime_camodel", "npu_drv", "stars", "model_top",
        "ascendcl", "error_manager", "profapi", "ge_common_base",
        "ascend_dump", "mmpa", "c_sec",
        "nnopbase",            # aclCreateTensor / aclDestroyTensor
        "opapi_transformer",   # aclnnFlashAttentionScore et al.
        "ascend_hal",
    ]

    cmd = [
        "g++", "-std=c++17", "-O2",
        "-I", str(repo_root / "include"),
        "-I", cann_inc,
        "-I", llvm_inc,
        "-I", llvm_build_inc,
        *sources,
        # Pull HostLaunchHelper + ExecutionSession + TaskGraph + SimBackend +
        # scheduler from the prebuilt static lib. Wrap with --whole-archive
        # off so only referenced objects are pulled in.
        ascendc_runtime_a,
        # LLVM support (llvm::json, MemoryBuffer, FileSystem, etc.)
        "-L", llvm_lib,
        "-lLLVMSupport",
        "-lLLVMDemangle",
        # CANN: simulator dir FIRST so libruntime_camodel.so resolves before
        # any real-NPU libruntime.so that lib64 also ships.
        "-L", sim_lib,
        "-L", cann_lib,      # lib64 first so libmetadef.so resolves here
        "-L", cann_devlib,   # x86_64 ascend_hal lives only here
    ]
    cmd += [f"-l{lib}" for lib in cann_libs]
    cmd += [f"-l{lib}" for lib in extra_libs]
    rpath = ":".join(filter(None, [sim_lib, cann_lib, cann_devlib]))
    cmd += [
        f"-Wl,-rpath,{rpath}",
        "-o", str(out_binary),
        "-pthread", "-lrt", "-lm", "-ldl",
    ]

    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True)
