add_subdirectory(AFIRToASCIR)
add_subdirectory(AFIRToASCIRText)
add_subdirectory(AscendCBufferPlacement)
add_subdirectory(AscendCFoldConcatAlloc)
add_subdirectory(LinalgToAscendC)
add_subdirectory(AscendCParallelize)
add_subdirectory(AscendCPrepareForEmit)
add_subdirectory(CanonicalizeCannSignature)
add_subdirectory(FuseGatherElementwise)
add_subdirectory(MarkStructuredOps)
add_subdirectory(Ascend)
