//===- AFIRTypes.td - AFIR dialect type definitions -------*- tablegen -*-===//
//
// Part of the Ascend-MLIR Project
//
//===----------------------------------------------------------------------===//
//
// This file defines types for the AFIR dialect.
//
//===----------------------------------------------------------------------===//

#ifndef AFIR_TYPES
#define AFIR_TYPES

include "Dialect/AFIR/AFIRBase.td"
include "mlir/IR/AttrTypeBase.td"

#endif // AFIR_TYPES