// Auto-generated by AclnnBackend. DO NOT EDIT.
// tilings_path: /home/gser/code/Ascend-MLIR/examples/dyn-bucketed-e2e/build_e2e/tilings_best.json
// kernel_binaries_dir: /home/gser/code/Ascend-MLIR/examples/dyn-bucketed-e2e/build_e2e/artifacts
#include "acl/acl.h"
#include "Runtime/AclnnOps.h"
#include "Runtime/Execution/HostLaunchHelper.h"
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <cstdlib>

using TensorInfo = mlir::runtime::aclnn::TensorInfo;
using mlir::runtime::aclnn::run_FlashAttentionScore;

static void network_impl(
    TensorInfo inputs[], int /*numInputs*/,
    TensorInfo outputs[], int /*numOutputs*/,
    aclrtStream stream) {
  TensorInfo t0[5] = {inputs[0], inputs[1], inputs[2], inputs[3], inputs[7]};
  TensorInfo t1[1] = {};
  t1[0].rank = 2;
  t1[0].shape[0] = t0[0].shape[0];
  t1[0].shape[1] = t0[0].shape[1];
  t1[0].dtype = 0;
  { size_t _n = 4; for (int _d = 0; _d < t1[0].rank; ++_d) _n *= (size_t)t1[0].shape[_d]; t1[0].data = ::operator new(_n); }
  if (mlir::runtime::hostLaunchAscendCKernel(
        "kernel_group0__v0",
        /*kernelBinariesDir=*/"/home/gser/code/Ascend-MLIR/examples/dyn-bucketed-e2e/build_e2e/artifacts",
        /*tilingsPath=*/"/home/gser/code/Ascend-MLIR/examples/dyn-bucketed-e2e/build_e2e/tilings_best.json",
        t0, 5, t1, 1) != 0) {
    fprintf(stderr, "hostLaunchAscendCKernel(kernel_group0__v0) failed\n");
    return;
  }
  TensorInfo t2[4] = {inputs[4], inputs[5], inputs[6], inputs[8]};
  TensorInfo t3[1] = {};
  t3[0].rank = 2;
  t3[0].shape[0] = t2[0].shape[0];
  t3[0].shape[1] = t2[0].shape[1];
  t3[0].dtype = 0;
  { size_t _n = 4; for (int _d = 0; _d < t3[0].rank; ++_d) _n *= (size_t)t3[0].shape[_d]; t3[0].data = ::operator new(_n); }
  if (mlir::runtime::hostLaunchAscendCKernel(
        "kernel_group1__v0",
        /*kernelBinariesDir=*/"/home/gser/code/Ascend-MLIR/examples/dyn-bucketed-e2e/build_e2e/artifacts",
        /*tilingsPath=*/"/home/gser/code/Ascend-MLIR/examples/dyn-bucketed-e2e/build_e2e/tilings_best.json",
        t2, 4, t3, 1) != 0) {
    fprintf(stderr, "hostLaunchAscendCKernel(kernel_group1__v0) failed\n");
    return;
  }
  outputs[0] = t1[0];
  outputs[1] = t3[0];
}

extern "C" void network(
    TensorInfo inputs[], int numInputs,
    TensorInfo outputs[], int numOutputs,
    aclrtStream stream) {
  // Try aclInit; if it fails (e.g. running on CPU sim with no NPU
  // device available), fall through in host-mode so aclnn ops dispatch
  // to AclnnOps.cpp's CPU-reference implementations.
  static bool initialized = false;
  if (!initialized) {
    initialized = true;
    const char *force = std::getenv("ASCEND_MLIR_FORCE_HOST_MODE");
    if (force && force[0] && force[0] != '0') {
      mlir::runtime::aclnn::setHostMode(true);
    } else {
      int rc = aclInit(nullptr);
      if (rc != ACL_SUCCESS && rc != ACL_ERROR_REPEAT_INITIALIZE) {
        mlir::runtime::aclnn::setHostMode(true);
      }
    }
  }
  network_impl(inputs, numInputs, outputs, numOutputs, stream);
}

extern "C" void network_set_dump_dir(const char *dir) {
  mlir::runtime::hostLaunchSetDumpIntermediatesDir(dir);
}
