// ============================================================
// tiling_func.mlir — Host-side tiling function for fc_relu kernel
//
// Inputs:  %M, %N, %K  (runtime tensor dimensions, i64)
// Outputs: TilingData struct with fields:
//            TB_M   — tile size along M for multi-core dispatch (level 1)
//            TB_N   — tile size along N for multi-core dispatch (level 1)
//            Tb_M   — tile size along M per AiCore (level 2)
//            Tb_N   — tile size along N per AiCore (level 2)
//            t_K    — tile size along K (cube inner loop, level 3)
//
// This function runs on the host CPU to compute tiling parameters from
// runtime shapes.  The inner algorithm is intentionally hardcoded to
// demonstrate the pipeline structure; a real compiler would solve an
// optimization problem here.
//
// The TilingData struct is passed to the device kernel via a GM pointer
// (ascir-translate emits emitasc.copy_struct to copy it into local memory).
// ============================================================

// TilingData layout (5 × i64 fields):
//   [0] TB_M   [1] TB_N   [2] Tb_M   [3] Tb_N   [4] t_K
!TilingData = !llvm.struct<"TilingData", (i64, i64, i64, i64, i64)>

module {

  // ----------------------------------------------------------
  // @tiling_func: compute tiling parameters from runtime shape
  // ----------------------------------------------------------
  func.func @tiling_func(%M: i64, %N: i64, %K: i64) -> !TilingData {

    // ── Hardware constants ────────────────────────────────────
    // Atlas 300I Duo / Ascend 910: 20 AiCores, L0A=L0B=256KB, L0C=512KB
    %CORE_NUM  = arith.constant 20  : i64
    %L0C_BYTES = arith.constant 524288 : i64   // 512 KB
    %BYTES_F32 = arith.constant 4   : i64      // f32 = 4 bytes
    %CUBE_UNIT = arith.constant 16  : i64      // cube unit = 16×16 block

    // ── t_K: K-axis tile size (cube inner loop) ───────────────
    // Fixed at 1 cube unit (16); real strategy would fit L0A/L0B.
    %t_K = arith.constant 16 : i64

    // ── Tb_M × Tb_N: per-AiCore tile (fits in L0C) ───────────
    // L0C holds Tb_M × Tb_N f32 elements.  Use 64×64 = 16384 elems = 64 KB.
    %Tb_M = arith.constant 64 : i64
    %Tb_N = arith.constant 64 : i64

    // ── TB_M × TB_N: level-1 dispatch tile ───────────────────
    // Each AiCore processes one (TB_M, TB_N) block.  We choose TB = Tb so
    // that the inner Tb loop runs exactly once per AiCore per dispatch.
    // A real heuristic would balance load across cores.
    %TB_M = arith.constant 64 : i64
    %TB_N = arith.constant 64 : i64

    // ── Pack into TilingData struct ───────────────────────────
    %td0 = llvm.mlir.undef : !TilingData
    %td1 = llvm.insertvalue %TB_M, %td0[0] : !TilingData
    %td2 = llvm.insertvalue %TB_N, %td1[1] : !TilingData
    %td3 = llvm.insertvalue %Tb_M, %td2[2] : !TilingData
    %td4 = llvm.insertvalue %Tb_N, %td3[3] : !TilingData
    %td5 = llvm.insertvalue %t_K,  %td4[4] : !TilingData

    return %td5 : !TilingData
  }

  // ----------------------------------------------------------
  // @runtime_dispatch: host-side launch entry point (conceptual)
  //
  // 1. Read runtime shapes.
  // 2. Call tiling_func to compute TilingData.
  // 3. Pass TilingData (via GM pointer) + tensor pointers to the kernel.
  //
  // In practice this is generated by the runtime framework; shown here
  // for documentation purposes.
  // ----------------------------------------------------------
  func.func @runtime_dispatch(
      %A:    memref<?x?xf32>,   // lhs matrix
      %B:    memref<?x?xf32>,   // rhs matrix
      %bias: memref<?x?xf32>,   // bias
      %out:  memref<?x?xf32>    // output
  ) {
    %c0 = arith.constant 0 : index
    %c1 = arith.constant 1 : index

    // ── Get runtime shapes ────────────────────────────────────
    %M_idx = memref.dim %A, %c0 : memref<?x?xf32>
    %K_idx = memref.dim %A, %c1 : memref<?x?xf32>
    %N_idx = memref.dim %B, %c1 : memref<?x?xf32>
    %M = arith.index_cast %M_idx : index to i64
    %K = arith.index_cast %K_idx : index to i64
    %N = arith.index_cast %N_idx : index to i64

    // ── Compute tiling parameters ─────────────────────────────
    %tiling = func.call @tiling_func(%M, %N, %K)
              : (i64, i64, i64) -> !TilingData

    // ── Unpack (for documentation / host-side logging) ────────
    %TB_M = llvm.extractvalue %tiling[0] : !TilingData
    %TB_N = llvm.extractvalue %tiling[1] : !TilingData
    %Tb_M = llvm.extractvalue %tiling[2] : !TilingData
    %Tb_N = llvm.extractvalue %tiling[3] : !TilingData
    %t_K  = llvm.extractvalue %tiling[4] : !TilingData

    // ── Launch kernel (conceptual placeholder) ────────────────
    // In a real AscendCL runtime:
    //   acl_launch_kernel("fc_relu", core_num,
    //                     A, B, bias, out, &tiling_data)
    // The kernel reads TilingData from GM using emitasc.copy_struct.

    return
  }

} // module
