function(resolve_ascend_cann_arch_dir out_var)
  set(_ascend_cann_arch "")
  if(CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|amd64)$")
    set(_ascend_cann_arch "x86_64-linux")
  elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "^(aarch64|arm64)$")
    set(_ascend_cann_arch "aarch64-linux")
  endif()
  set(${out_var} "${_ascend_cann_arch}" PARENT_SCOPE)
endfunction()
