// lib/Runtime/HostRunnerGen.cpp
#include "Runtime/HostRunnerGen.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Program.h"
#include "llvm/Support/raw_ostream.h"
#include <cstdlib>
#include <fstream>

namespace mlir::runtime {

static uint32_t magicForType(const std::string& kernel_type) {
  if (kernel_type == "cube") return 0x41494343u;
  return 0x41415246u; // "vec" and "mix" both use AIVEC
}

// Returns the complete runner.cpp source as a string.
// Splice points:
//   layout_init  : push_back lines for the default tiling_layout vector
//   magic_buf    : hex magic constant for DevBinary
//   kernel_name  : function name string literal
static std::string emitRunnerCpp(const HostRunnerGen::Config& cfg) {
  // Build push_back lines. Variable name in emitted code is "tiling_layout"
  // (matches the else-branch vector declaration in the emitted main()).
  std::string layout_init;
  for (size_t i = 0; i < cfg.tiling_layout.size(); ++i)
    layout_init += "    tiling_layout.push_back(\"" + cfg.tiling_layout[i] + "\");\n";

  char magic_buf[32];
  std::snprintf(magic_buf, sizeof(magic_buf), "0x%08X",
                magicForType(cfg.kernel_type));
  // Note: the 'u' unsigned suffix is appended by the raw string splice site below.

  // clang-format off
  return std::string(R"cpp(
// Auto-generated by HostRunnerGen. DO NOT EDIT.
// Compile: g++ -O2 -std=c++17 runner.cpp -ldl -o runner
#include <algorithm>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <dlfcn.h>
#include <fstream>
#include <iostream>
#include <regex>
#include <sstream>
#include <string>
#include <vector>

// ── Minimal .npy I/O ──────────────────────────────────────────────────────────

struct NDArray {
  void*                data  = nullptr;
  std::vector<int64_t> shape;
  int                  dtype = 0; // 0=f16 1=f32 2=i32
  size_t numElements() const {
    size_t n = 1;
    for (auto s : shape) n *= (size_t)s;
    return n;
  }
  size_t dtypeBytes() const { return dtype == 0 ? 2 : 4; }
  size_t nbytes()     const { return numElements() * dtypeBytes(); }
};

static bool loadNpy(const std::string& path, NDArray& arr) {
  std::ifstream f(path, std::ios::binary);
  if (!f) { std::cerr << "Cannot open: " << path << "\n"; return false; }
  char magic[6]; f.read(magic, 6);
  if (std::memcmp(magic, "\x93NUMPY", 6) != 0) {
    std::cerr << "Not a .npy file: " << path << "\n"; return false;
  }
  uint8_t major, minor;
  f.read((char*)&major, 1); f.read((char*)&minor, 1);
  uint32_t hlen = 0;
  if (major == 1) { uint16_t h; f.read((char*)&h, 2); hlen = h; }
  else { f.read((char*)&hlen, 4); }
  std::string header(hlen, '\0');
  f.read(header.data(), hlen);
  std::regex re_shape(R"('shape'\s*:\s*\(([^)]*)\))");
  std::smatch m;
  if (!std::regex_search(header, m, re_shape)) {
    std::cerr << "Cannot parse shape in: " << path << "\n"; return false;
  }
  std::istringstream ss(m[1].str()); std::string tok;
  while (std::getline(ss, tok, ',')) {
    tok.erase(0, tok.find_first_not_of(" \t"));
    tok.erase(tok.find_last_not_of(" \t,") + 1);
    if (!tok.empty()) arr.shape.push_back(std::stoll(tok));
  }
  std::regex re_dtype(R"('descr'\s*:\s*'([^']+)')");
  if (!std::regex_search(header, m, re_dtype)) {
    std::cerr << "Cannot parse dtype in: " << path << "\n"; return false;
  }
  std::string descr = m[1].str();
  if      (descr=="<f2"||descr=="=f2") arr.dtype = 0;
  else if (descr=="<f4"||descr=="=f4") arr.dtype = 1;
  else if (descr=="<i4"||descr=="=i4") arr.dtype = 2;
  else { std::cerr << "Unsupported dtype: " << descr << "\n"; return false; }
  arr.data = new uint8_t[arr.nbytes()];
  f.read((char*)arr.data, (std::streamsize)arr.nbytes());
  return true;
}

static bool saveNpy(const std::string& path, const NDArray& arr) {
  if (path == "/dev/null") return true;
  std::ofstream f(path, std::ios::binary);
  if (!f) { std::cerr << "Cannot write: " << path << "\n"; return false; }
  const char* descr = arr.dtype==0 ? "<f2" : (arr.dtype==1 ? "<f4" : "<i4");
  std::string shape_str = "(";
  for (size_t i = 0; i < arr.shape.size(); ++i) {
    shape_str += std::to_string(arr.shape[i]);
    if (arr.shape.size()==1 || i+1 < arr.shape.size()) shape_str += ",";
  }
  shape_str += ")";
  std::string dict = "{'descr': '" + std::string(descr) +
                     "', 'fortran_order': False, 'shape': " + shape_str + ", }";
  size_t total = 10 + dict.size() + 1;
  size_t pad   = (64 - total % 64) % 64;
  dict.append(pad, ' '); dict += '\n';
  uint16_t hlen = (uint16_t)dict.size();
  f.write("\x93NUMPY", 6); f.put(1); f.put(0);
  f.write((char*)&hlen, 2); f.write(dict.data(), dict.size());
  f.write((char*)arr.data, arr.nbytes());
  return true;
}

// ── Runtime API ───────────────────────────────────────────────────────────────

struct DevBinary {
  uint32_t magic; uint32_t version; const char* data; uint64_t length;
};

// ── Helpers ───────────────────────────────────────────────────────────────────

static std::vector<std::string> splitComma(const std::string& s) {
  std::vector<std::string> v;
  std::istringstream ss(s); std::string t;
  while (std::getline(ss, t, ',')) v.push_back(t);
  return v;
}

static std::vector<uint8_t> buildTiling(const std::string& params,
                                         const std::vector<std::string>& layout) {
  std::vector<uint8_t> bytes;
  auto pvec = splitComma(params);
  for (size_t i = 0; i < pvec.size(); ++i) {
    auto eq = pvec[i].find('=');
    int64_t val = std::stoll(pvec[i].substr(eq + 1));
    std::string type = i < layout.size() ? layout[i] : "int64";
    if (type == "int32" || type == "int32_t") {
      int32_t v = (int32_t)val; uint8_t buf[4];
      std::memcpy(buf, &v, 4); bytes.insert(bytes.end(), buf, buf+4);
    } else {
      uint8_t buf[8]; std::memcpy(buf, &val, 8);
      bytes.insert(bytes.end(), buf, buf+8);
    }
  }
  return bytes;
}

// ── Main ──────────────────────────────────────────────────────────────────────

int main(int argc, char** argv) {
  std::string bin_path, tiling_params, tiling_layout_str, inputs_str,
              output_path = "/dev/null";
  int block_dim = 1;

  for (int i = 1; i < argc; ++i) {
    std::string a = argv[i];
    auto next = [&]() -> std::string {
      if (i+1 >= argc) { std::cerr << "Missing arg after " << a << "\n"; exit(4); }
      return argv[++i];
    };
    if      (a == "--bin")           bin_path          = next();
    else if (a == "--tiling-params") tiling_params     = next();
    else if (a == "--tiling-layout") tiling_layout_str = next();
    else if (a == "--inputs")        inputs_str        = next();
    else if (a == "--output")        output_path       = next();
    else if (a == "--block-dim")     block_dim         = std::stoi(next());
  }
  if (bin_path.empty())  { std::cerr << "--bin required\n";    return 4; }
  if (inputs_str.empty()){ std::cerr << "--inputs required\n"; return 4; }

  // tiling layout: command-line overrides compiled-in default
  std::vector<std::string> tiling_layout;
  if (!tiling_layout_str.empty())
    tiling_layout = splitComma(tiling_layout_str);
  else {
)cpp") + layout_init + R"cpp(  }

  std::vector<uint8_t> tiling_bytes;
  if (!tiling_params.empty())
    tiling_bytes = buildTiling(tiling_params, tiling_layout);

  // Load inputs
  auto input_paths = splitComma(inputs_str);
  std::vector<NDArray> inputs(input_paths.size());
  for (size_t i = 0; i < input_paths.size(); ++i)
    if (!loadNpy(input_paths[i], inputs[i])) return 4;

  // Allocate output (single output; same shape/dtype as inputs[0])
  NDArray output;
  output.shape = inputs[0].shape;
  output.dtype = inputs[0].dtype;
  output.data  = new uint8_t[output.nbytes()]();

  // dlopen camodel
  const char* home = std::getenv("ASCEND_HOME_PATH");
  std::string lib_path = std::string(home ? home :
      "/usr/local/Ascend/ascend-toolkit/latest")
      + "/runtime/lib64/libruntime_camodel.so";
  void* lib = dlopen(lib_path.c_str(), RTLD_LAZY | RTLD_GLOBAL);
  if (!lib) { std::cerr << "dlopen failed: " << dlerror() << "\n"; return 3; }

#define LOAD(name, T) \
  auto name = reinterpret_cast<T>(dlsym(lib, #name)); \
  if (!name) { std::cerr << "dlsym " #name " failed\n"; dlclose(lib); return 3; }
  LOAD(rtSetDevice,         int(*)(int32_t))
  LOAD(rtDevBinaryRegister, int(*)(const DevBinary*, void**))
  LOAD(rtFunctionRegister,  int(*)(void*, void*, const char*, void*, uint32_t))
  LOAD(rtMalloc,            int(*)(void**, uint64_t, uint32_t, uint16_t))
  LOAD(rtFree,              int(*)(void*))
  LOAD(rtMemcpy,            int(*)(void*, uint64_t, const void*, uint64_t, uint32_t))
  LOAD(rtStreamCreate,      int(*)(void**, int32_t))
  LOAD(rtStreamDestroy,     int(*)(void*))
  LOAD(rtKernelLaunch,      int(*)(void*, uint32_t, void*, uint32_t, void*, void*))
  LOAD(rtDeviceSynchronize, int(*)())
#undef LOAD

  rtSetDevice(0);

  // Read binary
  std::ifstream bf(bin_path, std::ios::binary);
  if (!bf) { std::cerr << "Cannot open bin: " << bin_path << "\n"; return 4; }
  std::vector<uint8_t> bin_data((std::istreambuf_iterator<char>(bf)), {});

  // Register binary + function
  DevBinary dev_bin;
  dev_bin.magic   = )cpp") + std::string(magic_buf) + R"cpp(u;
  dev_bin.version = 0;
  dev_bin.data    = (const char*)bin_data.data();
  dev_bin.length  = bin_data.size();
  void* bin_handle = nullptr;
  if (rtDevBinaryRegister(&dev_bin, &bin_handle) != 0) {
    std::cerr << "rtDevBinaryRegister failed\n"; dlclose(lib); return 3;
  }
  const char* fn_name = ")cpp") + cfg.kernel_name + R"cpp(";
  void* fn_ptr = const_cast<char*>(fn_name);
  if (rtFunctionRegister(bin_handle, fn_ptr, fn_name, fn_ptr, 0) != 0) {
    std::cerr << "rtFunctionRegister failed\n"; dlclose(lib); return 3;
  }

  // Alloc helper: rtMalloc(n+512), align to 512 bytes, track raw ptr for rtFree
  struct AllocRec { void* raw; void* aligned; };
  std::vector<AllocRec> allocs;
  auto doAlloc = [&](size_t n) -> void* {
    void* raw = nullptr;
    rtMalloc(&raw, (uint64_t)(n + 512), 0u, (uint16_t)33u);
    uintptr_t a = ((uintptr_t)raw + 511) & ~511ULL;
    allocs.push_back({raw, (void*)a});
    return (void*)a;
  };
  auto freeAll = [&]() {
    for (auto& r : allocs) rtFree(r.raw);
    allocs.clear();
  };

  // H2D inputs
  std::vector<void*> in_ptrs, out_ptrs;
  for (auto& inp : inputs) {
    void* p = doAlloc(inp.nbytes());
    in_ptrs.push_back(p);
    const uint8_t* src = (const uint8_t*)inp.data;
    for (size_t off = 0; off < inp.nbytes(); off += 256) {
      size_t chunk = std::min<size_t>(256, inp.nbytes() - off);
      rtMemcpy((uint8_t*)p + off, chunk, src + off, chunk, 1);
    }
  }
  void* out_ptr = doAlloc(output.nbytes());
  out_ptrs.push_back(out_ptr);
  void* ws_ptr = doAlloc(8192);

  // Build launch args: [inputs..., outputs..., workspace, tiling_words...]
  std::vector<uint64_t> launch_args;
  for (auto* p : in_ptrs)  launch_args.push_back((uint64_t)p);
  for (auto* p : out_ptrs) launch_args.push_back((uint64_t)p);
  launch_args.push_back((uint64_t)ws_ptr);
  for (size_t i = 0; i < tiling_bytes.size(); i += 8) {
    uint64_t w = 0;
    std::memcpy(&w, tiling_bytes.data() + i,
                std::min<size_t>(8, tiling_bytes.size() - i));
    launch_args.push_back(w);
  }

  void* stream = nullptr;
  rtStreamCreate(&stream, 0);
  int rc = rtKernelLaunch(fn_ptr, (uint32_t)block_dim,
                          launch_args.data(),
                          (uint32_t)(launch_args.size() * 8),
                          nullptr, stream);
  if (rc != 0) {
    std::cerr << "rtKernelLaunch failed: rc=" << rc << "\n";
    rtStreamDestroy(stream); freeAll(); dlclose(lib); return 3;
  }
  rtDeviceSynchronize();
  rtStreamDestroy(stream);

  // D2H output (4-byte chunks; safe due to +512 overalloc)
  const uint8_t* src_d = (const uint8_t*)out_ptr;
  uint8_t* dst_d = (uint8_t*)output.data;
  for (size_t off = 0; off < output.nbytes(); off += 4) {
    uint8_t buf[4] = {};
    rtMemcpy(buf, 4, src_d + off, 4, 2);
    size_t chunk = std::min<size_t>(4, output.nbytes() - off);
    std::memcpy(dst_d + off, buf, chunk);
  }

  freeAll();
  saveNpy(output_path, output);
  dlclose(lib);
  return 0;
}
)cpp";
  // clang-format on
}

llvm::Expected<std::string> HostRunnerGen::Generate(const Config& cfg,
                                                     const std::string& output_dir) {
  // Guard: only num_outputs == 1 is supported
  if (cfg.num_outputs != 1)
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                   "HostRunnerGen: num_outputs=%d not supported "
                                   "(only 1 is currently implemented)",
                                   cfg.num_outputs);

  // Ensure output dir exists
  if (auto ec = llvm::sys::fs::create_directories(output_dir))
    return llvm::createStringError(ec, "Cannot create output dir: %s",
                                   output_dir.c_str());

  std::string src_path = output_dir + "/runner.cpp";
  std::string exe_path = output_dir + "/runner";

  // Write runner.cpp
  {
    std::ofstream f(src_path);
    if (!f)
      return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                     "Cannot write runner.cpp to: %s",
                                     src_path.c_str());
    f << emitRunnerCpp(cfg);
  }

  if (cfg.verbose)
    llvm::errs() << "[HostRunnerGen] Written: " << src_path << "\n";

  // Compile with g++ via /bin/sh -c (inherits PATH, which must include g++).
  // Use 300 s timeout consistent with Compiler.cpp.
  // If g++ is not on PATH, the error message will read "g++: not found".
  // In that case, add g++ to PATH or set its full path in this command.
  std::string cmd = "g++ -O2 -std=c++17 " + src_path + " -ldl -o " + exe_path;
  std::vector<std::string> args = {"/bin/sh", "-c", cmd};
  std::vector<llvm::StringRef> argv;
  for (auto& a : args) argv.push_back(a);

  std::string err_msg;
  std::optional<llvm::StringRef> redirects[3];
  int ret = llvm::sys::ExecuteAndWait(argv[0], argv, std::nullopt, redirects,
                                      /*secondsToWait=*/300, /*memoryLimit=*/0,
                                      &err_msg);
  if (ret != 0)
    return llvm::createStringError(llvm::inconvertibleErrorCode(),
                                   "g++ failed (exit %d): %s\n"
                                   "  cmd: %s",
                                   ret, err_msg.c_str(), cmd.c_str());

  if (cfg.verbose)
    llvm::errs() << "[HostRunnerGen] Compiled: " << exe_path << "\n";

  return exe_path;
}

} // namespace mlir::runtime
